- name: Validate variables for deploy_config.yml task
  ansible.builtin.assert:
    that:
      - nginx_file_owner is defined
      - nginx_file_group is defined
      - nginx_base_dir is defined
      - nginx is defined
      - nginx is mapping

- name: Deploy NGINX main config
  ansible.builtin.template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_base_dir }}/nginx.conf"
    owner: "{{ nginx_file_owner }}"
    group: "{{ nginx_file_group }}"
    mode: "0644"

- name: Deploy NGINX ACLs
  when:
    - nginx_acls is defined
    - nginx_acls is mapping
  ansible.builtin.template:
    src: "acl.j2"
    dest: "{{ nginx_base_dir }}/{{ nginx_acl }}"
    owner: "{{ nginx_file_owner }}"
    group: "{{ nginx_file_group }}"
    mode: "0644"
  vars:
    acl: "{{ nginx_acls[nginx_acl] }}"
  loop: "{{ nginx_acls.keys() | list }}"
  loop_control:
    loop_var: nginx_acl

- name: Validate NGINX configuration
  ansible.builtin.command: "nginx -t -c {{ nginx_base_dir }}/nginx.conf"
  register: nginx_validation
  failed_when: nginx_validation.rc != 0
  changed_when: false
