---
- name: Create nginx_action_list
  ansible.builtin.set_fact:
    nginx_action_list: "{{ nginx_actions.split(',') }}"

- name: Validate nginx_action_list
  ansible.builtin.assert:
    that:
      - nginx_action_list | length > 0
      - nginx_action_list | difference(nginx_supported_actions) | length == 0

- name: Deploy NGINX
  ansible.builtin.include_tasks: "{{ task_name }}.yml"
  loop: "{{ nginx_action_list }}"
  loop_control:
    loop_var: task_name
