---
- name: Converge
  hosts: all
  gather_facts: false
  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
      vars:
        nginx_actions: install,deploy_config,state_control
        nginx_state_action: started
        nginx_version: 1.24.0-2ubuntu7.8
        nginx:
          global:
            worker_processes: auto
          events:
            worker_connections: 1024
          http:
            include: mime.types
            default_type: application/octet-stream
